name: Comment on Issue Close

on:
  issues:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on Closed Issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `
              Thank you for your contribution! If you have any questions or need further assistance, feel free to reach out to us on our Discord server: [Discord](https://discord.gg/rZb46cCMmK). We have separate channels for all projects. Happy coding! 🚀

              Connect with us on social media:
              - **GitHub**: [ChromeGaming](https://github.com/ChromeGaming)
              - **LinkedIn**: [ChromeGaming](https://www.linkedin.com/company/chromegaming)
              - **Instagram**: [@chromegamingon](https://www.instagram.com/chromegamingon/)
              `
            });
            console.log(response);
